#!/bin/sh

pwd=$(pwd)
cd $(dirname $0)/../lib
db=$(basename $(dirname $(pwd)))
mkdir -p Schema/Result Schema/ResultSet
# -o constraint='qr/^[^(rotarians)]$/' # Rotarian.pm was needing to be custom for has_submission
# sub { warn "$_[0]\n"; return "_$_[1]" if grep { @o=split /\./; warn "$_ -- $o[0] eq $_[2]->{table_name} && $o[1] eq $_[1]\n"; $o[0] eq $_[2]->{table_name} && $o[1] eq $_[1] } qw/rotarians.has_submissions/; return undef; };
dbicdump -o dump_directory=. -o col_accessor_map='sub { return "_$_[1]" if $_[2]->{table_name} eq "rotarians" && grep { $_ eq $_[1] } qw/has_submissions/; return undef; }' -o default_resultset_class=ResultSet -o result_base_class='Schema::Result' -o components='["InflateColumn::DateTime", "Helper::Row::ToJSON"]' -o preserve_case=1 Schema dbi:mysql:database=${1:-$db} ${2:-$db} ${3:-$db} '{ quote_char => "`" }'
[ -d Schema/Result ] || exit

# This is no longer necessary now that default_resultset_class=ResultSet
exit
for i in Schema/Result/*.pm; do
[ -e $i ] || continue
j=$(basename $i .pm)
[ ! -e Schema/ResultSet/$j.pm ] && echo Writing Schema/ResultSet/$j.pm && cat << RESULTSET >> Schema/ResultSet/$j.pm
package Schema::ResultSet::$j;

use Modern::Perl;
use base 'Schema::ResultSet';

1;
RESULTSET
done
